version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: movie-review-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviereview
    ports:
      - "5438:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
