spring:
  datasource:
    url: jdbc:postgresql://db.ntglhgjaditddnaxeurv.supabase.co:5432/postgres
    username: postgres
    password: moviereview123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
